### ISSUE TITLE
Consistent Error Handling

### ISSUE THREAD

**Issue by traviscrist** [interledgerjs/ilp-protocol-stream#27]
On the connection and the stream we should match how node works with write() and only throw errors if there is not an `error` emitter present. Right now we throw errors regardless of the emitter being present and we do not emit errors if one is present. 

```javascript
if(this._events.error){
    this.safeEmit('error', streamClosedError)
}
```
Could be used to check if the error listener is present.

**Comment by sentientwaffle** [comment]
@traviscrist what `Connection`/`Stream` methods are you referring to? Most of the methods are async, so they don't `throw`, they return a rejecting `Promise`.

**Comment by traviscrist** [comment]
@sentientwaffle Honestly I don't fully recall the context or the goal behind this. I believe I wrote it up when I was comparing how a nodejs stream was working to ilp-protocolo-stream and this seemed to be a difference. 

@emschwartz do you recall any of the context behind this issue?

**Comment by emschwartz** [comment]
No idea
