### ISSUE TITLE
Should there be ACKs for data or should data only be sent in Prepare packets?

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-protocol-stream#5]
To figure out if the other side got a data frame, we can either:
- Send data frames only in Prepare packets and use the Fulfill/Reject as an acknowledgement (if the data is authenticated and we know it came from the receiver) 
  * If we do this, should we assume that a Reject is a NACK for the data, or should we assume they've gotten and processed the data even if the packet is rejected?
- Have ACK frames for data so that data can be sent in any type of ILP packet

Note that QUIC uses [ACK frames](https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#rfc.section.7.15) to acknowledge receipt of whole packets rather than specific frames or blocks of data.

**Comment by sharafian** [comment]
Given that the rules for data are different from the rules for money (successfully sending data while rejecting money is a reasonably common case), I think it makes sense to diverge from QUIC here and ACK on a per-frame basis

**Comment by emschwartz** [comment]
I think we should have it only send data on prepares and use ILP fulfills / rejects as ACKs. It simplifies the protocol and if we ever wanted to allow data to be sent in response packets we could add additional frames to handle this later.

Now the question is whether we should count ILP Reject packets that come from the receiver (and are authenticated so we know the prepare really made it to the receiver) as ACKs or NACKs. The data definitely got to the receiver, but they are rejecting the packet. Are they rejecting the data? I'm leaning towards saying that any reject is a rejection of the money as well as the data and the data should be resent. Thoughts?

**Comment by emschwartz** [comment]
This question has been answered for now. We'll track the implementation in https://github.com/interledgerjs/ilp-protocol-stream/issues/12
