### ISSUE TITLE
Inactivity Timeout

### ISSUE THREAD

**Issue by traviscrist** [interledgerjs/ilp-protocol-stream#51]
- [ ] Add an inactivityTimeout option to the stream connection. 
- [ ] If money is being transferred the timeout is reset.
- [ ] If no money is being transferred then the connection times out. 
- [ ] Leave timeout option as it.

**Comment by emschwartz** [comment]
Resolved by https://github.com/interledgerjs/ilp-protocol-stream/pull/62
