### ISSUE TITLE
What should ending a stream do if it still has money to send?

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-protocol-stream#6]
If you call `end` on a Node TCP socket, it will: 
1. Keep sending data until all the data written to it has been sent
1. Emit `'finish'` when it has finished sending all of the data
1. Emit `'end'` when the other side has indicated it is finished sending data
1. Emit `'close'` when the underlying socket is closed

If the other side isn't reading data from the socket and the reading side's buffer is full, the sending side will stay open until the consumer is finished. (See [this gist](https://gist.github.com/emschwartz/f62e8c7bb9d3d0a82b756a2d7095de6f) if you want to play around with different possibilities)

The question is what the behavior should be for a `DataAndMoneyStream` if you call `end` or `destroy` when it's still trying to send money? Should it close the stream immediately, wait until the money is sent, or close the stream only if the other side is currently blocking it from sending more money?

**Comment by emschwartz** [comment]
Another question in this vein: should we modify the `'finish'` and `'end'` events to refer to both money and data, or add separate events for when all of the money has been sent or when the other side has indicated that they won't be sending any more?

**Comment by sharafian** [comment]
I think it should close if it's in a stable state (the other side doesn't want to receive any more money), but otherwise should finish sending.

It might make sense to have a version of the function that force kills it, because it would be potentially bad if one person set their sendMax to Infinity, the other side had a receiveMax of Infinity, and there were no way to close it.

**Comment by emschwartz** [comment]
We could have `stream.destroy([error])` do the force close, like in normal streams. That causes the other side to emit `'error'`, `'finish'`, `'close'`

**Comment by sentientwaffle** [comment]
I think that `'finish'` and `'end'` should trigger when both the money & data are finished/ended.

If it becomes necessary later, `money:{finish,end}`/`data:{finish,end}` events could be added on, but I think they are less useful.

**Comment by emschwartz** [comment]
Bidirectional Node streams can receive data even after one side has called `end`. 

What should happen if the other side sends money after you call `end`? Should it accept packets with money and data until the other side has said they are finished or should it start rejecting them right away? I'm leaning towards letting it accept packets until both sides are done and saying that if you want to close it immediately you should call `destroy` instead of `end`.

**Comment by emschwartz** [comment]
There are now separate `end` and `destroy` methods and the events are emitted in a similar fashion to node streams
