### ISSUE TITLE
Default flow control values

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-protocol-stream#7]
Like QUIC, STREAM is going to have connection- and stream-level flow control (so both sides will be able to control both the amount of data they're getting for each stream and for the connection as a whole).

1. What should the default buffer size be for each stream? Node streams default to 16kb. However, STREAM packets can carry up to ~32kb so using the Node default would make the receiver reject a full STREAM packet.
1. What should the default maximum number of open streams be? 10 per side?
1. What should the default buffer size be for an entire connection (the total of the buffered data in all of the open streams)?

**Comment by dappelt** [comment]
From a security perspective, you want to avoid that an attacker with few resources can allocate a lot of the peer's resources.

Some questions that come to my mind. Regarding 1., can different streams of the same connection share a buffer or should each stream have an exclusive buffer? 

An exclusive buffer would be quite taxing on the memory footprint of a connection. If you want the buffer to be big enough to store several max. size ILP packets, say 5, and there are max. 10 streams, the buffer size for a connection would be ~32kb * 5 * 10 = ~1.6Mb.

On the other hand, having a shared buffer for all streams of a connection is more efficient, but I assume also more complicated to implement.

**Comment by emschwartz** [comment]
> can different streams of the same connection share a buffer or should each stream have an exclusive buffer?

There isn't actually a buffer that's allocated until data comes in for the specific streams.

We can set a connection-level limit that's different than the sum of the max for the number of open streams. The question is what that limit should be to avoid letting attackers use too much of the server's resources.
