### ISSUE TITLE
Try compiling using Assemblyscript?

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-protocol-stream#99]
Curious if this would provide any performance benefits: https://github.com/AssemblyScript/assemblyscript

**Comment by traviscrist** [comment]
I think there would be performance benefits but I don't think we can just use it as STREAM is currently written since there is not async await in AssemblyScript yet: https://github.com/AssemblyScript/assemblyscript/issues/376

**Comment by emschwartz** [comment]
Good point! I'll close this now then since that's definitely a blocker
